### ISSUE TITLE
`qpy` doesn't percolate delay gate's units

### ISSUE THREAD

**Issue by vtomole** [Qiskit/qiskit-terra#10662]
### Environment

- **Qiskit Terra version**:  `0.25.0`
- **Python version**:  `3.10`
- **Operating system**:  `Ubuntu`

### What is happening?

When a delay gate is created with units that are not `dt`, qpy doesn't keep track of the units.

### How can we reproduce the issue?

```python
import qiskit
from qiskit import qpy

qc = qiskit.QuantumCircuit(1)
qc.delay(10, unit="s")

print(qc)
# prints
#     ┌──────────────┐
#  q: ┤ Delay(10[s]) ├
#     └──────────────┘
# c: 1/════════════════


with open('delay.qpy', 'wb') as fd:
    qpy.dump(qc, fd)

with open('delay.qpy', 'rb') as fd:
    new_qc = qpy.load(fd)[0]
    
    
print(new_qc)
# prints
#     ┌───────────────┐
#  q: ┤ Delay(10[dt]) ├
#     └───────────────┘
#  c: 1/═════════════════

print(str(qc) == str(new_qc))
# prints
# False
```

### What should happen?

`print(str(qc) == str(new_qc))` should print `True`

**Comment by Abhiraj-Shrotriya** [comment]
@jakelishman  Can you please assign me this issue and issue #10582 ? I can fix try and fix both since they both require modification of `qpy`.

**Comment by jakelishman** [comment]
@Abhiraj-Shrotriya: sure, I can assign you.  This should hopefully be relatively simple change, though we'll need to be careful with backwards compatibility of the format.

**Comment by Abhiraj-Shrotriya** [comment]
@jakelishman I have fixed the issue. But I am having problems making the `CIRCUIT_INSTRUCTION_V2` in `qpy/binaryio/formats.py` backwards compatible since `unit_size` must be added to it. 

Should I make a V3 for it?

something like this:

```
# CIRCUIT_INSTRUCTION_V2
CIRCUIT_INSTRUCTION_V2 = namedtuple(
    "CIRCUIT_INSTRUCTION",
    [
        "name_size",
        "label_size",
        "num_parameters",
        "num_qargs",
        "num_cargs",
        "has_condition",
        "condition_register_size",
        "condition_value",
        "num_ctrl_qubits",
        "ctrl_state",
        "unit_size",
    ],
)
CIRCUIT_INSTRUCTION_V2_PACK = "!HHHII?HqIII"
CIRCUIT_INSTRUCTION_V2_SIZE = struct.calcsize(CIRCUIT_INSTRUCTION_V2_PACK)
```

**Comment by jakelishman** [comment]
Yeah, I think we'll need to make a `CIRCUIT_INSTRUCTION_V3`, because this problem actually runs deeper than just `Delay`; there's a `duration` and `unit` field on _all_ `Instruction` instances not just `Delay`, which QPY is currently ignoring, resulting in things like #10582.  The complete solution is to add serialisation for those two fields to all instructions, and that'll definitely need the new `CIRCUIT_INSTRUCTION` version.

**Comment by Abhiraj-Shrotriya** [comment]
My method adds the unit field for _all_ `Instruction`. My code has solved most of the problems suggested by you. 

I will now work towards creating a `CIRCUIT_INSTRUCTION_V3`.

Any more suggestions?

**Comment by Abhiraj-Shrotriya** [comment]
@jakelishman 
Hi,
I was a little busy for the past few days but now I can work towards making a Pull Request. The work is almost over. 
I am sorry for the delay. I aim to make a pull request soon.

I just wanted to ask how to implement qpy version control.

Thank you.

**Comment by ihincks** [comment]
This issue still exists in 2.4.1 and has acquired a new failure mode, I believe, introduced by f047aaf.

Before this commit, the Rust reader always wrapped the duration in a `ParameterExpression`, which happened to bypass `Delay.validate_parameter`'s integer check, so a float-duration delay would load without crashing (with the wrong unit).

Now, `qpy.load` returns without raising, but the circuit is internally inconsistent: the Rust layer stores e.g. `Param::Float(100.5)` with `DelayUnit::DT`. Iterating `circuit.data` from Python raises `CircuitError` because `Delay.validate_parameter` rejects a non-integer duration with `unit='dt'`. 
```python
import io
from qiskit import QuantumCircuit, qpy

qc = QuantumCircuit(1)
qc.delay(100.5, 0, unit="ns")

buf = io.BytesIO()
qpy.dump(qc, buf); buf.seek(0)
qc2 = qpy.load(buf)[0]   # no exception raised

# CircuitError: "Integer duration is expected for 'dt' unit."
[inst.operation for inst in qc2.data] 
```

Notice that Rust-space tools, for example the QASM3 exporter, may  bypass `validate_parameter` and silently do weird stuff:

```python
from qiskit import qasm3

out = qasm3.dumps_experimental(qc2)
delay_line = next(l for l in out.splitlines() if "delay" in l)
print(delay_line)   # 'delay[100.5dt]'  <-- wrong unit, no error
```
