### ISSUE TITLE
Flattened conditional circuits give incorrect results

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-terra#6583]
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

Flattening a conditional circuit gives incorrect results. It looks like the issue is probably in how the conditionals are implemented:

### Steps to reproduce the problem

Manually adding an additional registers to a teleport circuit works:
 
```python
def teleport_circuit():
    """Teleport qubit 0 -> 2"""
    qr = QuantumRegister(3)
    c0 = ClassicalRegister(1)
    c1 = ClassicalRegister(1)
    teleport = QuantumCircuit(qr, c0, c1)
    teleport.h(qr[1])
    teleport.cx(qr[1], qr[2])
    teleport.cx(qr[0], qr[1])
    teleport.h(qr[0])
    teleport.measure(qr[0], c0[0])
    teleport.measure(qr[1], c1[0])
    teleport.z(qr[2]).c_if(c0, 1)
    teleport.x(qr[2]).c_if(c1, 1)
    return teleport

# Add extra register for measuring qubit-2
c2 = ClassicalRegister(1)
circ = teleport_circuit()
circ.add_register(c2)
circ.measure(2, c2)

# Run
counts = AerSimulator().run(circ).result().get_counts(0)
marginal_counts(counts, [2])

# Marginal Counts (correct)
{'0': 1024}
```

But composing and flattening gives wrong answer:
```python
# Compose with larger circuit
circ = QuantumCircuit(3, 3)
circ = circ.compose(teleport_circuit(), range(3), range(2))
circ.measure(2, 2)

# Run
counts = AerSimulator().run(circ).result().get_counts(0)
marginal_counts(counts, [2])

# Marginal Counts (incorrect)
{'1': 228, '0': 796}
```

### What is the expected behavior?

Flattening the conditional circuit should implement the same circuit.

### Suggested solutions

From the drawer it looks liek the flattened circuit is handling conditions on the joint circuit wrong:
```
                    ┌───┐┌─┐              
q_0: ────────────■──┤ H ├┤M├──────────────
     ┌───┐     ┌─┴─┐└┬─┬┘└╥┘              
q_1: ┤ H ├──■──┤ X ├─┤M├──╫───────────────
     └───┘┌─┴─┐└───┘ └╥┘  ║  ┌───┐  ┌───┐ 
q_2: ─────┤ X ├───────╫───╫──┤ Z ├──┤ X ├─
          └───┘       ║   ║  └─╥─┘  └─╥─┘ 
                      ║   ║ ┌──╨──┐┌──╨──┐
c: 3/═════════════════╩═══╩═╡ = 1 ╞╡ = 2 ╞
                      1   0 └─────┘└─────┘
```
Looks like conditions are triggering on creg values `01` and `10`, but nothing on `11` which should trigger both conditional gates.

Looking at the qobj that gets assembled from these circuits we can see the difference:

Multi-register assembled qobj instructions:
`assemble(circ).experiments[0].instructions = `
```
[QasmQobjInstruction(name='h', qubits=[1]),
 QasmQobjInstruction(name='cx', qubits=[1, 2]),
 QasmQobjInstruction(name='cx', qubits=[0, 1]),
 QasmQobjInstruction(name='h', qubits=[0]),
 QasmQobjInstruction(name='measure', qubits=[0], register=[0], memory=[0]),
 QasmQobjInstruction(name='measure', qubits=[1], register=[1], memory=[1]),
 QasmQobjInstruction(name='bfunc', register=3, mask="0x1", relation="==", val="0x1"),
 QasmQobjInstruction(name='z', qubits=[2], conditional=3),
 QasmQobjInstruction(name='bfunc', register=4, mask="0x2", relation="==", val="0x2"),
 QasmQobjInstruction(name='x', qubits=[2], conditional=4),
 QasmQobjInstruction(name='measure', qubits=[2], register=[2], memory=[2])]
```

Flattened circuit assembled qobj instructions:
```
[QasmQobjInstruction(name='h', qubits=[1]),
 QasmQobjInstruction(name='cx', qubits=[1, 2]),
 QasmQobjInstruction(name='cx', qubits=[0, 1]),
 QasmQobjInstruction(name='h', qubits=[0]),
 QasmQobjInstruction(name='measure', qubits=[0], register=[0], memory=[0]),
 QasmQobjInstruction(name='measure', qubits=[1], register=[1], memory=[1]),
 QasmQobjInstruction(name='bfunc', register=3, mask="0x7", relation="==", val="0x1"),
 QasmQobjInstruction(name='z', qubits=[2], conditional=3),
 QasmQobjInstruction(name='bfunc', register=4, mask="0x7", relation="==", val="0x2"),
 QasmQobjInstruction(name='x', qubits=[2], conditional=4),
 QasmQobjInstruction(name='measure', qubits=[2], register=[2], memory=[2])]
```

You can see that in the second case the `mask` value is being set incorrectly to `0x7 = 0b111` in both case to the full 3-bit register rather than the the single bit values.

**Comment by chriseclectic** [comment]
Follow up building with a flat circuit this way looks to give correct result:
```python
teleport = QuantumCircuit(3, 2)
teleport.h(1)
teleport.cx(1, 2)
teleport.cx(0, 1)
teleport.h(0)
teleport.measure(0, 0)
teleport.measure(1, 1)
creg = teleport.cregs[0]
teleport.z(2).c_if(creg[0], 1)
teleport.x(2).c_if(creg[1], 1)

# Compose with another circuit
circ = QuantumCircuit(3, 3)
circ = circ.compose(teleport, range(3), range(2))
circ.measure(2, 2)
```

assembled qobj
```
[QasmQobjInstruction(name='h', qubits=[1]),
 QasmQobjInstruction(name='cx', qubits=[1, 2]),
 QasmQobjInstruction(name='cx', qubits=[0, 1]),
 QasmQobjInstruction(name='h', qubits=[0]),
 QasmQobjInstruction(name='measure', qubits=[0], register=[0], memory=[0]),
 QasmQobjInstruction(name='measure', qubits=[1], register=[1], memory=[1]),
 QasmQobjInstruction(name='bfunc', register=3, mask="0x1", relation="==", val="0x1"),
 QasmQobjInstruction(name='z', qubits=[2], conditional=3),
 QasmQobjInstruction(name='bfunc', register=4, mask="0x2", relation="==", val="0x2"),
 QasmQobjInstruction(name='x', qubits=[2], conditional=4),
 QasmQobjInstruction(name='measure', qubits=[2], register=[2], memory=[2])]
```

**Comment by kdk** [comment]
I believe this is an issue in `QuantumCircuit.compose` failing to map the condition correctly from the two single-bit cregs in the input circuit onto the one larger creg on the output circuit. Before #6018 , it wouldn't have been possible to map these conditions and I would've expected `.compose` to raise similar to how `circuit_to_instruction(teleport_circuit())` currently raises: `"Cannot convert condition in circuit with multiple classical registers to instruction"`.

After #6018 , this should at least be possible for the case where gates are conditioned on a single `Clbit`. @TharrmashasthaPV , do you have an idea how this might look?

The drawing error I believe is fixed by #6261 .

**Comment by TharrmashasthaPV** [comment]
I think that this trouble is not just with single-bit cregs. For instance take the following circuit
```python
q = QuantumRegister(2)
c = ClassicalRegister(2)
qc = QuantumCircuit(q, c)
qc.h(0).c_if(c, 1)

circ = QuantumCircuit(3,3)
circ = circ.compose(qc, [0,1], [1,2])
```
This circuit outputs `assemble(circ).experiments[0].instructions` as 
```
[QasmQobjInstruction(name='bfunc', register=3, mask="0x7", relation="==", val="0x2"), 
QasmQobjInstruction(name='h', qubits=[0], conditional=3)]
```
This error seems to happen whenever a circuit `qc` containing a creg, say `c`, is composed to a circuit that contains a single creg whose size is larger than that of `c`.

As for the conditioning on single `Clbit`, currently a type check is performed to see if the condition is on a `ClassicalRegister` or `Clbit` before the condition is mapped to the new_cregs. I guess that's why `teleport.z(2).c_if(c0, 1)` returns a circuit with an incorrect mapping while `teleport.z(2).c_if(creg[0], 1)` outputs a correct circuit.

However, we could extend the type checking to also check if the conditioned register is of length 1 and then if the length was 1, then mapping of condition could proceed similar to that done for a `Clbit` condition. Something like 
```python
if isinstance(condition[0], Clbit):
    cond_creg = [condition[0]]
elif len(list(condition[0]))==1:
    cond_creg = list(condition[0])
else:
    cond_creg = condition[0]
    is_reg = True
...
```
in line [584](https://github.com/Qiskit/qiskit-terra/blob/5fad07e9c537e7f254cbd099e129a1eb427176cd/qiskit/dagcircuit/dagcircuit.py#L584) in the `_map_condition()` in `DAGCircuit` class should do the job I guess.

**Comment by jakelishman** [comment]
The drawer issue will be fixed by #7285.

**Comment by chriseclectic** [comment]
Bumping this again because its still an issue (see https://github.com/Qiskit/qiskit-experiments/issues/943 for more details).

The core issue seems to be if I have `circuit1` with multiple registers and conditionals on them, and then i initialize `circuit2` with a single flat conditional and compose circuit1 into it, the conditionals get expanded to conditionals of the full classical register of circuit2, but using only the bit value of the original register expanded with zeros across the other bits. What should happen is it should trigger regardless of values on the other bits, not just when they are zero.

Eg to use the teleport example:
```python
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
qr = QuantumRegister(3, 'qr')
c0 = ClassicalRegister(1, 'c0')
c1 = ClassicalRegister(1, 'c1')
circuit1 = QuantumCircuit(qr, c0, c1)
circuit1.h(1)
circuit1.cx(1, 2)
circuit1.cx(0, 1)
circuit1.h(0)
circuit1.measure(0, c0)
circuit1.measure(1, c1)
circuit1.z(2).c_if(c0, 1)
circuit1.x(2).c_if(c1, 1)
circuit1.draw()
```
```
                     ┌───┐┌─┐          
qr_0: ────────────■──┤ H ├┤M├──────────
      ┌───┐     ┌─┴─┐└┬─┬┘└╥┘          
qr_1: ┤ H ├──■──┤ X ├─┤M├──╫───────────
      └───┘┌─┴─┐└───┘ └╥┘  ║ ┌───┐┌───┐
qr_2: ─────┤ X ├───────╫───╫─┤ Z ├┤ X ├
           └───┘       ║   ║ └─╥─┘└─╥─┘
  c0: ═════════════════╬═══╩═══■════╬══
                       ║      0x1   ║  
  c1: ═════════════════╩════════════■══
                                   0x1 
```

Composing with a flat register
```python
circuit2 = QuantumCircuit(3, 2)
circuit2.compose(circuit1, inplace=True)
circuit2.draw()
```
gives
```
circuit2 = QuantumCircuit(3, 2)

circuit2.compose(circuit1, inplace=True)

circuit2.draw()

                    ┌───┐┌─┐          
q_0: ────────────■──┤ H ├┤M├──────────
     ┌───┐     ┌─┴─┐└┬─┬┘└╥┘          
q_1: ┤ H ├──■──┤ X ├─┤M├──╫───────────
     └───┘┌─┴─┐└───┘ └╥┘  ║ ┌───┐┌───┐
q_2: ─────┤ X ├───────╫───╫─┤ Z ├┤ X ├
          └───┘       ║   ║ └─╥─┘└─╥─┘
c_0: ═════════════════╬═══╩═══■════o══
                      ║       ║    ║  
c_1: ═════════════════╩═══════o════■══
                             0x1  0x2 
```

Composing with an enlarged register
```python
circuit3 = QuantumCircuit(3, 4)
circuit3.compose(circuit1, clbits=[0, 1], inplace=True)
circuit3.draw()
```
gives
```
                    ┌───┐┌─┐          
q_0: ────────────■──┤ H ├┤M├──────────
     ┌───┐     ┌─┴─┐└┬─┬┘└╥┘          
q_1: ┤ H ├──■──┤ X ├─┤M├──╫───────────
     └───┘┌─┴─┐└───┘ └╥┘  ║ ┌───┐┌───┐
q_2: ─────┤ X ├───────╫───╫─┤ Z ├┤ X ├
          └───┘       ║   ║ └─╥─┘└─╥─┘
c_0: ═════════════════╬═══╩═══■════o══
                      ║       ║    ║  
c_1: ═════════════════╩═══════o════■══
                              ║    ║  
c_2: ═════════════════════════o════o══
                              ║    ║  
c_3: ═════════════════════════o════o══
                             0x1  0x2 
```

**Comment by jakelishman** [comment]
I will prepare a fix for this for Terra 0.23.  There's other stuff in `compose` that's likely to cause issues as well, and I'll try and get it all in one thump.

**Comment by jakelishman** [comment]
I've made #9206 that should fix this.  Just to note: the drawers don't handle overlapping registers correctly, so it may well still _look_ like there's an issue, but if you inspect the objects to look in their conditions, registers and the bits in those conditions, you should find it's correct.

I've checked that the Aer simulations at the top work as expected with them, but I can't make any promises about how well it'll serialise to actual backends - I'm not sure how well the aliasing register model will transport.
